# ポート番号だけ違うもの
services:
  api_develop:
    build:
      context: .  # プロジェクトルートをビルドコンテキストとして指定
      dockerfile: develop_docker/Dockerfile.develop  # Dockerfileへの相対パス
    ports:
      - "7783:7783"  # 左テスト環境用のポート
    volumes:
      - ./app:/app
    environment:
      - ENVIRONMENT=develop
      - MAX_FILE_SIZE=100000000
      - TEMP_DIR=/app/temp
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 384M
    command: [
      "uvicorn",
      "main:app",
      "--host", "0.0.0.0",
      "--port", "7783",
      "--timeout-keep-alive", "6000",
      "--workers", "2",
      "--limit-concurrency", "3",
      "--backlog", "2"
    ]
